name: archlinux_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: archlinux

    steps:
      - uses: actions/checkout@v2
      - name: Display usage !
        run: bash ezdump -h
      - name: Run the script !
        run: bash ezdump

