name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dox2unix
        run: sudo apt-get install -y dos2unix
      - name: Display usage !
        run: bash ezdump -h
      - name: Run the script !
        run: bash ezdump

